"""user_id_is_nulleable_refresh

Revision ID: addf4c592881
Revises: 400cde4d06aa
Create Date: 2026-01-02 14:45:21.442841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addf4c592881'
down_revision: Union[str, Sequence[str], None] = '400cde4d06aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('access_tokens', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_tokens', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('access_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
