from enum import Enum


class ExceptionCode(str, Enum):
    UNAUTHORIZED = "UNAUTHORIZED"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    FORBIDDEN = "FORBIDDEN"
    PERMISSION_REQUIRED = "PERMISSION_REQUIRED"
    ROLE_REQUIRED = "ROLE_REQUIRED"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    UNAUTHORIZED_CLIENT = "UNAUTHORIZED_CLIENT"
